# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  ubuntu:
    machine:
      image: ubuntu-2204:2022.04.1



jobs:
  build_and_test:
    executor: ubuntu
    steps:
      - checkout
      - run:
          command: PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public yarn install
          name: Run install
      - run:
          command: yarn test
          name: Run Tests


workflows:
  # Name the workflow "welcome"
  node:
    # Run the welcome/run job in its own container
    jobs:
      - build_and_test

